### ISSUE TITLE
Improve debuggability of frontend

### ISSUE THREAD

**Issue by Ma27** [squirrel-labs/ratatosk#68] opened 2020-04-24 22:41 UTC
While working on #67 I realized that a lot of debug-related tasks during a development-cycle are pretty much tied to a trial-and-error approach.

I gathered a few suggestions what we can improve (enhancements and corrections to this list are always welcome):

* [ ] Investigate chrome's debugging feature. On my `chromium` I was able to jump into `.rs`-files(!) when setting a breakpoint in a JS-file that invokes rust-code. We should check whether we can optimize the generation of our wasm-blobs to improve this feature for development.

* [ ] Make use of multiple profiles: use all debug-related features of `wasm-bindgen` for development and enable all useful optimizations for a release-build (see also #63). I implemented a first step towards this in a0ee624420c53395c45c558483e9ad91ab1c6bae.

* [ ] Find a way to easily introspect `.wat`-files. Reading those in e.g. `vim` is not the best way when having files with too many indentation levels.

* [x] Make logging easier. Maybe I was just too stupid, but in some cases you want a fairly cheap log-to-console mechanism for debugging purposes and this seemed rather weird to me when dealing with Rust code that is supposed to be compiled into wasm.

**Comment by TrueDoctor** [comment] 2020-04-25 02:45
FYI I've tried to enable rust file debugging in `12406404d57276c35e02170e0555d3e5c3f84c4a` by exporting dwarf data but this got previously destroyed by wasm-bindgen, I'll check tomorrow if I can reproduce the debugging with the new version. 
In that commit I added many comfort features, such as symbol export and de mangeling of function names to get usable stack traces.
I've also added a panic handler.
debugging can be done by calling `log::debug!("hi{}",val)` or using panic, but that requires heap allocations. We found this to be of little help while debugging the allocator, hence the static log message in our alloc module.
logging is inherently not cheap since every call to log invokes the js `console.log` function.
I'd advise against debugging wat files directly due to the metric tone of boilerplate code and multiple optimization runs (`rustc`, `llvm`, `wasm-bindgen`, `wasm-opt`).
chromes debugging features should provide an easier approach

**Comment by Ma27** [comment] 2020-04-25 11:02
First of all, I'm not that advanced with WASM as you are, so sorry if I bring up some obvious stuff again :) 

> FYI I've tried to enable rust file debugging in 12406404d57276c35e02170e0555d3e5c3f84c4a by exporting dwarf data but this got previously destroyed by wasm-bindgen, I'll check tomorrow if I can reproduce the debugging with the new version.

Do you remember which version broke this? I used `--keep-debug` from `wasm-bindgen` (at version 0.2.60) for DWARF-symbols. However the support in chromium just seemed "half-baked" as I couldn't introspect variables and call stacks.

Will do some more research soon (unless you're faster of course :p).

>  logging is inherently not cheap since every call to log invokes the js console.log function.

Agreed, there's a reason why you usually decrease the log-level in productive systems :) 

I'd consider this more of a convenience feature for debugging/testing.

> 'd advise against debugging wat files directly due to the metric tone of boilerplate code and multiple optimization runs (rustc, llvm, wasm-bindgen, wasm-opt).

Yeah, those files were pretty hard to read which is why I moved on with other approaches yesterday. Unless there's a (preferably graphical) tool to introspect those files (after e.g. an unoptimized debug build), I fully agree.

**Comment by Ma27** [comment] 2020-04-25 11:02
(will respond to the rest here later this weekend btw)

**Comment by TrueDoctor** [comment] 2020-04-25 13:02
> Do you remember which version broke this? I used `--keep-debug` from wasm-bindgen (at version 0.2.60) for DWARF-symbols. However the support in chromium just seemed "half-baked" as I couldn't introspect variables and call stacks.

as far as I'm aware, introspecting variables will be quite hard, because you cannot simply move things like strings from rust to js. 
I was using this: https://developers.google.com/web/updates/2019/12/webassembly
as a reference and overlooked the --keep debug feature in wasm-bindgen as the guide was outdated

> Agreed, there's a reason why you usually decrease the log-level in productive systems :)

I think you can set the log level in logic/graphics `entries.rs` 
> I'd consider this more of a convenience feature for debugging/testing.

Of course, just as an anecdote: when logging every key event, the logic thread spends more than 100% of its cycle time just calling the log function. Each call to any js function results in about `1-2 ms` of overhead
`--keep-debug` seems like a worthy addition, in conjunction with profiles alluded to in #63 
We made it a lot harder on ourselves than nessesary

**Comment by TrueDoctor** [comment] 2020-06-09 10:16
As we no longer use wasm bindgen, the dwarf sections are removed due to maually sed'ing the wat file. Until we find a better soltion for that, I'll close this isse for now until we find a better solution

**Closed by TrueDoctor** 2020-06-09 10:16 UTC
Labels: documentation, enhancement, frontend
